data_aug:
  prob: 0.3
dataloaders:
  num_workers: 4
  train_batch_size: 64
  val_batch_size: 128
dataset:
  challenge_name: MulticlassClassification
  mean:
  - 155.3132
  - 128.6486
  - 127.0073
  stddev:
  - 64.12
  - 58.4539
  - 60.8631
  use_masks: false
experiment_name: multiclass_efficient_nofreeze_multisteplr01_dropout
model:
  dropout: 0.2
  freeze_weights: false
  model_name: efficient
  num_classes: 3
  num_frozen_layers: None
training:
  best_metric: kappa
  criterion: CrossEntropyLoss
  criterion_args:
    weight:
    - 0.46615505706414795
    - 0.607831562377017
    - 0.9260133805588351
  lr_scheduler: MultiStepLR
  lr_scheduler_args:
    gamma: 0.1
    milestones:
    - 10
    - 25
    - 30
    - 45
  n_epochs: 50
  optimizer: SGD
  optimizer_args:
    lr: 0.01
    momentum: 0.9
  resume_training: false
